name: Website CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: website

jobs:
  website-changes:
    runs-on: ubuntu-latest

    outputs:
      website: ${{ steps.filter.outputs.website }}

    steps:
    - uses: actions/checkout@v7
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          website:
            - 'website/**'
            - '.github/workflows/website.yml'

  website-build:
    needs: website-changes
    if: needs.website-changes.outputs.website == 'true'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v6
      with:
        node-version: 24.x
        cache: 'npm'
        cache-dependency-path: website/package-lock.json
    - run: npm ci
    - run: npm run build
